### ISSUE TITLE
Can't bind to 80

### ISSUE THREAD

**Issue by maddox** [RaymondMouthaan/sonweb-docker#2]
I'm bringing up this container and it doesn't seem to want to start. I'm not sure why it can't bind to port 80. 

I have nginx running on another container on port 80 that is exposed as port 80 to the host, but I wouldn't think that would make a difference inside the sonweb container.

Here's my log:

```
Changed server name to 'sonoff.mydomain'...
Clearing any old processes...
Starting apache...
(98)Address in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
```

Here's my docker compose config:

```
  sonoff:
    image: raymondmm/sonweb
    container_name: sonoff
    restart: always
    network_mode: host
    ports:
      - 5008:80
    hostname: sonoff
    environment:
      - APACHE_SERVER_NAME=sonoff.mydomain
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - $SERVICE_ROOT/sonoff:/data
    logging:
      driver: json-file
      options:
        max-size: 50m
```
